### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by danjee** [jboss-remoting/jboss-remoting#68]
Sorry for using the github issue tracker for this but documentation is pretty scarse for this project. Also on the jboss forums the activity is very low. 
Are there any samples available for using the remoting to work just like Java RMI (registering a class with interface for server and on client side calling methods on that proxy interface) ?

**Comment by dmlloyd** [comment]
No, JBoss Remoting is not an RPC protocol; it's a multiplex layer for other message-oriented protocols to share a socket with concurrent message support.  It is possible to implement RPC on top of it (this is essentially what the EJB protocol is), but EJB is the only one we have at present.

The reason that activity is low is because it has grown into a very internal project, used to underpin several of our services but generally hidden from users.

**Comment by danjee** [comment]
Thank you for your fast response. I was afraid of this. I will search for other alternatives. I really liked the features remoting3 brought.
